allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
supportedArchitectures:
  os:
    - linux
    - darwin
  cpu:
    - x64
    - arm64
  libc:
    - musl
    - glibc
minimumReleaseAgeExclude:
  - "@vitest/expect@4.1.7"
  - "@vitest/mocker@4.1.7"
  - "@vitest/pretty-format@4.1.7"
  - "@vitest/runner@4.1.7"
  - "@vitest/snapshot@4.1.7"
  - "@vitest/spy@4.1.7"
  - "@vitest/utils@4.1.7"
  - vitest@4.1.7
  - semver@7.8.1
  - terser@5.48.0
  - comment-parser@1.4.7
  - date-fns@4.3.0
  - tinyexec@1.2.2
  - tinyglobby@0.2.9
  - tinyrainbow@1.2.0
  - '@types/node@25.9.3'
  - '@vue/compiler-core@3.5.38'
  - '@vue/compiler-dom@3.5.38'
  - '@vue/compiler-sfc@3.5.38'
  - '@vue/compiler-ssr@3.5.38'
  - '@vue/reactivity@3.5.38'
  - '@vue/runtime-core@3.5.38'
  - '@vue/runtime-dom@3.5.38'
  - '@vue/server-renderer@3.5.38'
  - '@vue/shared@3.5.38'
  - vue@3.5.38
